---
- hosts: dev
  become: yes
  tasks: 
    - name: Install docker
      yum: 
        name: docker
        state: present
    - name: start Docker
      service:
        name: docker
        state: started
    - name: Install python3-pip
      yum: 
        name: python3-pip
        state: present
    - name: Install docker-py via pip
      pip: 
        name: docker-py
        state: present
    - name: start container
      docker_container:
        name: webapp_py
        image: "sidverse/webapp:{{}}"
        state: started